//! Measures bundle capacity: recall of `Codebook::decode` (iterative top-k from the integer
//! accumulator) against bundle size `k` and codebook size `n`, for each dimension.
//!
//! Deterministic: codebook vectors come from the seeded encoder and member choice from a fixed
//! xorshift stream, so the table is reproducible byte for byte. Regenerate docs/hdc-capacity.md:
//!
//! ```text
//! cargo run --release -p instinct-hdc --example capacity > docs/hdc-capacity.md
//! ```

use std::fmt::Write as _;

use instinct_core::Millis;
use instinct_hdc::{Accumulator, Codebook, D1024, D2048, D4096, Dim, Encoder};

const TRIALS: u64 = 10;
const SIZES: [usize; 3] = [64, 256, 1024];
const BUNDLES: [usize; 6] = [1, 5, 15, 50, 100, 200];

fn xorshift(state: &mut u64) -> u64 {
    *state ^= *state << 13;
    *state ^= *state >> 7;
    *state ^= *state << 17;
    *state
}

/// Recall in per-mille (members recovered / members bundled, over all trials) for
/// (iterative decode from the accumulator, one-shot top-k by similarity to the thresholded
/// bundle).
fn recall<D: Dim>(book: &Codebook<D>, n: usize, k: usize) -> (u64, u64) {
    let mut state = 0x9e37_79b9_7f4a_7c15 ^ (n as u64) << 8 ^ k as u64;
    let (mut hit, mut hit_sign, mut total) = (0u64, 0u64, 0u64);
    for _ in 0..TRIALS {
        let mut members: Vec<usize> = Vec::with_capacity(k);
        while members.len() < k {
            let m = usize::try_from(xorshift(&mut state) % n as u64).unwrap_or(0);
            if !members.contains(&m) {
                members.push(m);
            }
        }
        let mut acc = Accumulator::<D>::new();
        for &m in &members {
            if let Some(v) = book.vector(m) {
                acc.add(v, 1);
            }
        }
        let got = book.decode(&acc, k, Millis::MIN);
        hit += got.iter().filter(|(i, _)| members.contains(i)).count() as u64;
        let sign = acc.to_hv();
        let mut ranked: Vec<(i16, usize)> = book
            .vectors()
            .iter()
            .enumerate()
            .map(|(i, v)| (-sign.similarity(v).get(), i))
            .collect();
        ranked.sort_unstable();
        hit_sign += ranked[..k]
            .iter()
            .filter(|(_, i)| members.contains(i))
            .count() as u64;
        total += k as u64;
    }
    (hit * 1000 / total.max(1), hit_sign * 1000 / total.max(1))
}

fn table<D: Dim>(out: &mut String) {
    let enc = Encoder::new("capacity", 1);
    let _ = writeln!(out, "\n## D = {}\n", D::BITS);
    let _ = write!(out, "| n \\ k |");
    for k in BUNDLES {
        let _ = write!(out, " {k} |");
    }
    let _ = write!(out, "\n|---|");
    for _ in BUNDLES {
        let _ = write!(out, "---|");
    }
    out.push('\n');
    for n in SIZES {
        let book = Codebook::<D>::new((0..n).map(|i| {
            let id = format!("item{i:05}");
            let v = enc.encode(&id);
            (id, v)
        }))
        .unwrap_or_else(|e| unreachable!("generated ids are unique and non-empty: {e}"));
        let _ = write!(out, "| {n} |");
        for k in BUNDLES {
            if k > n {
                let _ = write!(out, " – |");
                continue;
            }
            let (r, s) = recall(&book, n, k);
            let _ = write!(out, " {}.{}% / {}.{}% |", r / 10, r % 10, s / 10, s % 10);
        }
        out.push('\n');
    }
}

fn main() {
    let mut out = String::from(
        "# HDC capacity (measured)\n\n\
         Generated by `cargo run --release -p instinct-hdc --example capacity`; do not edit by hand.\n\n\
         Each cell: **decode recall / sign recall** when `k` distinct codebook entries (of `n`)\n\
         are bundled with weight 1, over 10 deterministic trials. *Decode* is the iterative\n\
         top-k of `Codebook::decode` (reads the integer accumulator and subtracts each found\n\
         member; floor = −1000). *Sign* is one-shot top-k by similarity to the thresholded\n\
         bundle, the textbook capacity measure, shown for contrast: it is why spec §4.5 says\n\
         to decode from the accumulator.\n\n\
         Capacity is measured, not assumed (spec §4.5). Use the table to pick `D` for a\n\
         pack's codebook size and expected bundle size; a cell below 100% means decode can\n\
         return a non-member, so packs must keep the profile's similarity floor and margin\n\
         checks in front of any HDC answer.\n",
    );
    table::<D1024>(&mut out);
    table::<D2048>(&mut out);
    table::<D4096>(&mut out);
    // The table is the program's output: stdout is the documented interface here.
    #[allow(clippy::print_stdout)]
    {
        print!("{out}");
    }
}
